pipeline {
    agent any

    tools{
        maven "mvn"
    }

    stages{

        stage('Build'){

            steps{
                git 'https://github.com/jenkins-docs/simple-java-maven-app'

                bat 'mvn clean test package'
            }
        }
    }   
}
